### ISSUE TITLE
cygwin support

### ISSUE THREAD

**Issue by cjfp** [flac123/flac123#1]
I got flac123 to work under Cygwin with:

1) setup-x86_64.exe -n -q -P flac-devel libao-devel libpopt-devel

2) add the following to configure.ac
```
CYGWIN*)
    AC_DEFINE_UNQUOTED(AUDIO_DEFAULT, "wmm",[Define the default libao output device.])
    ;;
```  
3) autoreconf -vif

**Comment by flac123** [comment]
Thanks for submitting this.
You also uncovered a lack of a default case expression for unrecognized systems.
Cygwin support will be "best effort" in terms of my test matrix.

**Comment by cjfp** [comment]
Thanks for the fix!  A default case of oss instead of a build error seems right.  And understood about Cygwin; if I encounter anything I'll send more portability fixes.
