### ISSUE TITLE
Use of Ftol metadata block

### ISSUE THREAD

**Issue by ktmf01** [flac123/flac123#3]
Hi,

I'm currently trying to clean up this list: https://xiph.org/flac/id.html Specifially, this is about the Ftol item on the list, which is referenced  in this document:

https://github.com/flac123/flac123/blob/f55c1e392e0497d78f9c215081bae40ad833bc16/old/doc/metadata#L2

Do you have any idea what this block is supposed to do and whether it is still in use?

**Comment by kerneljake** [comment]
Sorry, I do not know the origin of this block ID.  This is the first I have heard about it, honestly.  It must have been requested by the previous maintainer.  It seems it would only be useful to an application that writes metadata blocks, but flac123 is not one of those applications.  That ID has never been used by flac123, and it is safe to deallocate it.

**Comment by kerneljake** [comment]
OK to close?

**Comment by ktmf01** [comment]
Yeah, sure
