### ISSUE TITLE
automake too old?

### ISSUE THREAD

**Issue by evertverduin** [flac123/flac123#5]
root@streamPie:/home/pi/flac123# make
 cd . && /bin/bash /home/pi/flac123/missing automake-1.16 --foreign
configure.ac:6: error: version mismatch.  This is Automake 1.16.5,
configure.ac:6: but the definition used by this AM_INIT_AUTOMAKE
configure.ac:6: comes from Automake 1.16.1.  You should recreate
configure.ac:6: aclocal.m4 with aclocal and run automake again.
WARNING: 'automake-1.16' is probably too old.
         You should only need it if you modified 'Makefile.am' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'automake' program is part of the GNU Automake package:
         <https://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <https://www.gnu.org/software/autoconf>
         <https://www.gnu.org/software/m4/>
         <https://www.perl.org/>
make: *** [Makefile:297: Makefile.in] Error 1
root@streamPie:/home/pi/flac123#

**Comment by kerneljake** [comment]
This is a packaging [problem](https://stackoverflow.com/a/40964543/7015912) I need to fix.  To get you up and running, can you run `autoreconf -fi` followed by `automake` and then `autoconf`.  After that, `./configure` and `make` should work.

Once you get it working, please send me the output of either `lsb_release -a` or `cat /etc/*release` so I can reproduce it on the same Raspberry Pi OS you have.

**Comment by kerneljake** [comment]
You may need to install autoconf (using the package manager of your choice) to get `autoreconf -fi` to work.

**Comment by evertverduin** [comment]
Problem solved! Sorry for the late reaction!
